/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package takehomeassignment;

import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class AdminViewFrame extends javax.swing.JFrame {

    int mousepX;
    int mousepY;
    /**
     * Creates new form AdminViewFrame
     */
    ArrayList<Student> stList;
    ArrayList<UndergraduateStudent> UstList;
    ArrayList<PostgraduateStudent> PstList;
    ArrayList<Lecturer> LecList;
    ArrayList<Instructor> InsList;
    ArrayList<Subject> SubjectList;
    ArrayList<StudentCourseReg> CourseRegList;
    ArrayList<Marks> MarksList;
    DBOperation dbOps = new DBOperation();

    public AdminViewFrame() {
        initComponents();
        loadStudent();
        loadUndergraduateStudent();
        loadPostgraduateStudent();
        loadLecturer();
        loadInstructor();
        loadSubject();
        loadCourseReg();
        loadMarkSheet();
    }

    void loadStudent() {
        stList = dbOps.getStudent();
        StudentDetails stDetails = new StudentDetails(stList);
        tblStudent.setModel(stDetails);
    }

    void loadUndergraduateStudent() {
        UstList = dbOps.getUndergraduateStudent();
        UndergraduateStudentDetails UstDetails = new UndergraduateStudentDetails(UstList);
        tblUndergraduateStudent.setModel(UstDetails);
    }

    void loadPostgraduateStudent() {
        PstList = dbOps.getPostgraduateStudent();
        PostgraduateStudentDetails PstDetails = new PostgraduateStudentDetails(PstList);
        tblPostgraduateStudent.setModel(PstDetails);
    }

    void loadLecturer() {
        LecList = dbOps.getLecturer();
        LecturerDetails LecDetails = new LecturerDetails(LecList);
        tblLecturer.setModel(LecDetails);
    }

    void loadInstructor() {
        InsList = dbOps.getInstructor();
        InstructorDetails InsDetails = new InstructorDetails(InsList);
        tblInstructer.setModel(InsDetails);
    }

    void loadSubject() {
        SubjectList = dbOps.getSubject();
        SubjectDetails SubDetails = new SubjectDetails(SubjectList);
        tblSubject.setModel(SubDetails);
    }

    void loadCourseReg() {
        CourseRegList = dbOps.getCourseReg();
        CourseRegDetails CourseDetails = new CourseRegDetails(CourseRegList);
        tblCourseReg.setModel(CourseDetails);
    }

    public void loadMarkSheet() {
        MarksList = dbOps.getMarks();
        MarksDetails MarksD = new MarksDetails(MarksList);
        tblMarks.setModel(MarksD);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTopBar2 = new javax.swing.JPanel();
        lblMinimize3 = new javax.swing.JLabel();
        lblClose3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanelBackground = new javax.swing.JPanel();
        jPanal = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        btnAddStudent = new javax.swing.JButton();
        btnUpdateStudent = new javax.swing.JButton();
        btnDeleteStudent = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudent = new javax.swing.JTable();
        btnViewStudent = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUndergraduateStudent = new javax.swing.JTable();
        btnViewUndegraduateStudent = new javax.swing.JButton();
        btnUpdateUndegraduateStudent = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPostgraduateStudent = new javax.swing.JTable();
        btnViewPostgraduateStudent = new javax.swing.JButton();
        btnUpdatePostgraduateStudent = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnAddLecturer = new javax.swing.JButton();
        btnViewLecturer = new javax.swing.JButton();
        btnUpdateLecturer = new javax.swing.JButton();
        btnDeleteLecturer = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblLecturer = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btnAddInstructor = new javax.swing.JButton();
        btnViewInstructor = new javax.swing.JButton();
        btnUpdateInstructor = new javax.swing.JButton();
        btnDeleteInstructor = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblInstructer = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        btnAddSubject = new javax.swing.JButton();
        btnViewSubject = new javax.swing.JButton();
        btnUpdateSubject = new javax.swing.JButton();
        btnDeleteSubject = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblSubject = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        btnDeleteCourseReg = new javax.swing.JButton();
        btnNotPay = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnPayed = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        tblCourseReg = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        btnAddMarks = new javax.swing.JButton();
        btnUpdateMarks = new javax.swing.JButton();
        btnRemoveMarks = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblMarks = new javax.swing.JTable();
        btnSendEmail1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnMainMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTopBar2.setBackground(new java.awt.Color(102, 255, 102));
        jPanelTopBar2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblMinimize3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblMinimize3.setForeground(new java.awt.Color(102, 102, 255));
        lblMinimize3.setText("-");
        lblMinimize3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimize3MouseClicked(evt);
            }
        });

        lblClose3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblClose3.setForeground(new java.awt.Color(102, 102, 255));
        lblClose3.setText("x");
        lblClose3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClose3MouseClicked(evt);
            }
        });

        jLabel15.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel15MouseDragged(evt);
            }
        });
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel15MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTopBar2Layout = new javax.swing.GroupLayout(jPanelTopBar2);
        jPanelTopBar2.setLayout(jPanelTopBar2Layout);
        jPanelTopBar2Layout.setHorizontalGroup(
            jPanelTopBar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopBar2Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 1156, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblMinimize3)
                .addGap(10, 10, 10)
                .addComponent(lblClose3)
                .addContainerGap())
        );
        jPanelTopBar2Layout.setVerticalGroup(
            jPanelTopBar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopBar2Layout.createSequentialGroup()
                .addGroup(jPanelTopBar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMinimize3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblClose3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelTopBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nsbm.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Admin");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/admin 2.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Art.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(195, 195, 195))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1380, 110));

        jPanelBackground.setBackground(new java.awt.Color(204, 255, 204));
        jPanelBackground.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 51)));

        jPanal.setForeground(new java.awt.Color(0, 153, 153));
        jPanal.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        btnAddStudent.setBackground(new java.awt.Color(31, 58, 147));
        btnAddStudent.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddStudent.setForeground(new java.awt.Color(255, 255, 255));
        btnAddStudent.setText("Add Student");
        btnAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudentActionPerformed(evt);
            }
        });

        btnUpdateStudent.setBackground(new java.awt.Color(31, 58, 147));
        btnUpdateStudent.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdateStudent.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateStudent.setText("Update Student");
        btnUpdateStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStudentActionPerformed(evt);
            }
        });

        btnDeleteStudent.setBackground(new java.awt.Color(31, 58, 147));
        btnDeleteStudent.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDeleteStudent.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteStudent.setText("Delete Student");
        btnDeleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteStudentActionPerformed(evt);
            }
        });

        tblStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStudent);

        btnViewStudent.setBackground(new java.awt.Color(31, 58, 147));
        btnViewStudent.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnViewStudent.setForeground(new java.awt.Color(255, 255, 255));
        btnViewStudent.setText("View Student");
        btnViewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnAddStudent)
                        .addGap(18, 18, 18)
                        .addComponent(btnViewStudent)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateStudent)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteStudent)))
                .addGap(21, 21, 21))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanal.addTab("Student", jPanel3);

        jPanel8.setBackground(new java.awt.Color(204, 204, 255));

        tblUndergraduateStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblUndergraduateStudent);

        btnViewUndegraduateStudent.setBackground(new java.awt.Color(31, 58, 147));
        btnViewUndegraduateStudent.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnViewUndegraduateStudent.setForeground(new java.awt.Color(255, 255, 255));
        btnViewUndegraduateStudent.setText("View Student");
        btnViewUndegraduateStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewUndegraduateStudentActionPerformed(evt);
            }
        });

        btnUpdateUndegraduateStudent.setBackground(new java.awt.Color(31, 58, 147));
        btnUpdateUndegraduateStudent.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdateUndegraduateStudent.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateUndegraduateStudent.setText("Update Student");
        btnUpdateUndegraduateStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUndegraduateStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(btnViewUndegraduateStudent)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateUndegraduateStudent)))
                .addGap(18, 18, 18))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewUndegraduateStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateUndegraduateStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanal.addTab("Undergraduate Student", jPanel8);

        jPanel9.setBackground(new java.awt.Color(204, 204, 255));

        tblPostgraduateStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblPostgraduateStudent);

        btnViewPostgraduateStudent.setBackground(new java.awt.Color(31, 58, 147));
        btnViewPostgraduateStudent.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnViewPostgraduateStudent.setForeground(new java.awt.Color(255, 255, 255));
        btnViewPostgraduateStudent.setText("View Student");
        btnViewPostgraduateStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPostgraduateStudentActionPerformed(evt);
            }
        });

        btnUpdatePostgraduateStudent.setBackground(new java.awt.Color(31, 58, 147));
        btnUpdatePostgraduateStudent.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdatePostgraduateStudent.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdatePostgraduateStudent.setText("Update Student");
        btnUpdatePostgraduateStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePostgraduateStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(btnViewPostgraduateStudent)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdatePostgraduateStudent))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewPostgraduateStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdatePostgraduateStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanal.addTab("Postgraduate Student", jPanel9);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        btnAddLecturer.setBackground(new java.awt.Color(31, 58, 147));
        btnAddLecturer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddLecturer.setForeground(new java.awt.Color(255, 255, 255));
        btnAddLecturer.setText("Add Lecturer");
        btnAddLecturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLecturerActionPerformed(evt);
            }
        });

        btnViewLecturer.setBackground(new java.awt.Color(31, 58, 147));
        btnViewLecturer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnViewLecturer.setForeground(new java.awt.Color(255, 255, 255));
        btnViewLecturer.setText("View Lecturer");
        btnViewLecturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewLecturerActionPerformed(evt);
            }
        });

        btnUpdateLecturer.setBackground(new java.awt.Color(31, 58, 147));
        btnUpdateLecturer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdateLecturer.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateLecturer.setText("Update Lecturer");
        btnUpdateLecturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateLecturerActionPerformed(evt);
            }
        });

        btnDeleteLecturer.setBackground(new java.awt.Color(31, 58, 147));
        btnDeleteLecturer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDeleteLecturer.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteLecturer.setText("Delete Lecturer");
        btnDeleteLecturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteLecturerActionPerformed(evt);
            }
        });

        tblLecturer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblLecturer);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnAddLecturer)
                        .addGap(18, 18, 18)
                        .addComponent(btnViewLecturer)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateLecturer)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteLecturer)))
                .addGap(21, 21, 21))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddLecturer, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateLecturer, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteLecturer, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewLecturer, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanal.addTab("Lecturer", jPanel4);

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));

        btnAddInstructor.setBackground(new java.awt.Color(31, 58, 147));
        btnAddInstructor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddInstructor.setForeground(new java.awt.Color(255, 255, 255));
        btnAddInstructor.setText("Add Instructor");
        btnAddInstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddInstructorActionPerformed(evt);
            }
        });

        btnViewInstructor.setBackground(new java.awt.Color(31, 58, 147));
        btnViewInstructor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnViewInstructor.setForeground(new java.awt.Color(255, 255, 255));
        btnViewInstructor.setText("View Instructor");
        btnViewInstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewInstructorActionPerformed(evt);
            }
        });

        btnUpdateInstructor.setBackground(new java.awt.Color(31, 58, 147));
        btnUpdateInstructor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdateInstructor.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateInstructor.setText("Update Instructor");
        btnUpdateInstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateInstructorActionPerformed(evt);
            }
        });

        btnDeleteInstructor.setBackground(new java.awt.Color(31, 58, 147));
        btnDeleteInstructor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDeleteInstructor.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteInstructor.setText("Delete Instructor");
        btnDeleteInstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteInstructorActionPerformed(evt);
            }
        });

        tblInstructer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tblInstructer);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnAddInstructor)
                        .addGap(18, 18, 18)
                        .addComponent(btnViewInstructor)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateInstructor)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteInstructor)))
                .addGap(21, 21, 21))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanal.addTab("Instructor", jPanel5);

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));

        btnAddSubject.setBackground(new java.awt.Color(31, 58, 147));
        btnAddSubject.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddSubject.setForeground(new java.awt.Color(255, 255, 255));
        btnAddSubject.setText("Add Subject");
        btnAddSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSubjectActionPerformed(evt);
            }
        });

        btnViewSubject.setBackground(new java.awt.Color(31, 58, 147));
        btnViewSubject.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnViewSubject.setForeground(new java.awt.Color(255, 255, 255));
        btnViewSubject.setText("View Subject");
        btnViewSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSubjectActionPerformed(evt);
            }
        });

        btnUpdateSubject.setBackground(new java.awt.Color(31, 58, 147));
        btnUpdateSubject.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdateSubject.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateSubject.setText("Update Subject");
        btnUpdateSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateSubjectActionPerformed(evt);
            }
        });

        btnDeleteSubject.setBackground(new java.awt.Color(31, 58, 147));
        btnDeleteSubject.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDeleteSubject.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteSubject.setText("Delete Subject");
        btnDeleteSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSubjectActionPerformed(evt);
            }
        });

        tblSubject.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tblSubject);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnAddSubject)
                        .addGap(18, 18, 18)
                        .addComponent(btnViewSubject)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateSubject)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteSubject)))
                .addGap(21, 21, 21))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanal.addTab("Subject", jPanel6);

        jPanel7.setBackground(new java.awt.Color(204, 204, 255));

        btnDeleteCourseReg.setBackground(new java.awt.Color(31, 58, 147));
        btnDeleteCourseReg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDeleteCourseReg.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteCourseReg.setText("Delete CourseReg");
        btnDeleteCourseReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCourseRegActionPerformed(evt);
            }
        });

        btnNotPay.setBackground(new java.awt.Color(31, 58, 147));
        btnNotPay.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNotPay.setForeground(new java.awt.Color(255, 255, 255));
        btnNotPay.setText("Not Pay");
        btnNotPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotPayActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(0, 204, 51));
        jLabel6.setText(" Mark here some student  Pay or Not  each semester");

        btnPayed.setBackground(new java.awt.Color(31, 58, 147));
        btnPayed.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPayed.setForeground(new java.awt.Color(255, 255, 255));
        btnPayed.setText("Payed");
        btnPayed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayedActionPerformed(evt);
            }
        });

        tblCourseReg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(tblCourseReg);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteCourseReg)
                    .addComponent(jLabel6)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnPayed)
                        .addGap(18, 18, 18)
                        .addComponent(btnNotPay)))
                .addGap(21, 21, 21))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnDeleteCourseReg, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNotPay, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPayed, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanal.addTab("Course Registration", jPanel7);

        jPanel10.setBackground(new java.awt.Color(204, 204, 255));

        btnAddMarks.setBackground(new java.awt.Color(31, 58, 147));
        btnAddMarks.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddMarks.setForeground(new java.awt.Color(255, 255, 255));
        btnAddMarks.setText("Add Marks");
        btnAddMarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMarksActionPerformed(evt);
            }
        });

        btnUpdateMarks.setBackground(new java.awt.Color(31, 58, 147));
        btnUpdateMarks.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdateMarks.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateMarks.setText("Update Marks");
        btnUpdateMarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateMarksActionPerformed(evt);
            }
        });

        btnRemoveMarks.setBackground(new java.awt.Color(31, 58, 147));
        btnRemoveMarks.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRemoveMarks.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoveMarks.setText("RemoveMarks");
        btnRemoveMarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveMarksActionPerformed(evt);
            }
        });

        tblMarks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "cIndexNo", "cSemester", "cSub1", "cSub2", "cSub3", "cSub4", "cSub5", "cSub6", "cGPA", "cEmail", "cSendOrNot"
            }
        ));
        tblMarks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMarksMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(tblMarks);

        btnSendEmail1.setBackground(new java.awt.Color(0, 153, 153));
        btnSendEmail1.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        btnSendEmail1.setForeground(new java.awt.Color(255, 255, 255));
        btnSendEmail1.setText("Send Email");
        btnSendEmail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendEmail1ActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(0, 204, 51));
        jLabel7.setText("For send Email, select the Row");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(btnSendEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(btnAddMarks)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateMarks)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemoveMarks)))
                .addGap(21, 21, 21))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemoveMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSendEmail1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanal.addTab("Marks", jPanel10);

        jPanel1.setBackground(new java.awt.Color(37, 116, 169));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Aug.png"))); // NOI18N

        btnMainMenu.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        btnMainMenu.setForeground(new java.awt.Color(0, 153, 153));
        btnMainMenu.setText("Main Menu");
        btnMainMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel4)
                .addGap(65, 65, 65)
                .addComponent(btnMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(256, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelBackgroundLayout = new javax.swing.GroupLayout(jPanelBackground);
        jPanelBackground.setLayout(jPanelBackgroundLayout);
        jPanelBackgroundLayout.setHorizontalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackgroundLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jPanal, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanelBackgroundLayout.setVerticalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackgroundLayout.createSequentialGroup()
                .addGap(0, 115, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanal, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanal.getAccessibleContext().setAccessibleName("AdminArea");

        getContentPane().add(jPanelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, -1));

        setSize(new java.awt.Dimension(1219, 687));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblMinimize3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimize3MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimize3MouseClicked

    private void lblClose3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClose3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblClose3MouseClicked

    private void jLabel15MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseDragged
        int cordinateX = evt.getXOnScreen();
        int cordinateY = evt.getYOnScreen();

        this.setLocation(cordinateX - mousepX, cordinateY - mousepY);
    }//GEN-LAST:event_jLabel15MouseDragged

    private void jLabel15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_jLabel15MousePressed

    private void btnViewSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSubjectActionPerformed
        ViewSubjectFrame viewC = new ViewSubjectFrame();
        viewC.setVisible(true);
        viewC.setFields(SubjectList.get(tblSubject.getSelectedRow()));
        viewC.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnViewSubjectActionPerformed

    private void btnAddSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSubjectActionPerformed
        SubjectFrame newCourse = new SubjectFrame();
        newCourse.setVisible(true);
        newCourse.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        newCourse.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
            }

            @Override
            public void windowClosing(WindowEvent e) {
                setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            }

            @Override
            public void windowClosed(WindowEvent e) {
                loadSubject();
            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
        });
    }//GEN-LAST:event_btnAddSubjectActionPerformed

    private void btnAddInstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddInstructorActionPerformed
        InstructorFrame newIns = new InstructorFrame();
        newIns.setVisible(true);
        newIns.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        newIns.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
            }

            @Override
            public void windowClosing(WindowEvent e) {
            }

            @Override
            public void windowClosed(WindowEvent e) {
                loadInstructor();
            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
        });
    }//GEN-LAST:event_btnAddInstructorActionPerformed

    private void btnAddLecturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLecturerActionPerformed
        LecturerFrame newLec = new LecturerFrame();
        newLec.setVisible(true);
        newLec.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        newLec.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
            }

            @Override
            public void windowClosing(WindowEvent e) {
            }

            @Override
            public void windowClosed(WindowEvent e) {
                loadLecturer();
            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
        });
    }//GEN-LAST:event_btnAddLecturerActionPerformed

    private void btnViewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewStudentActionPerformed
        ViewStudentFrame viewStd = new ViewStudentFrame();
        viewStd.setVisible(true);
        viewStd.setFields(stList.get(tblStudent.getSelectedRow()));
        viewStd.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnViewStudentActionPerformed

    private void btnDeleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteStudentActionPerformed
        DeleteStudentFrame deleteStd = new DeleteStudentFrame();
        deleteStd.setVisible(true);
        deleteStd.setFields(stList.get(tblStudent.getSelectedRow()));
        //deleteStd.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        deleteStd.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
            }

            @Override
            public void windowClosing(WindowEvent e) {
            }

            @Override
            public void windowClosed(WindowEvent e) {
                loadStudent();
                loadUndergraduateStudent();
                loadPostgraduateStudent();
            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
        });
    }//GEN-LAST:event_btnDeleteStudentActionPerformed

    private void btnUpdateStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStudentActionPerformed
        UpdateStudentFrame updateStd = new UpdateStudentFrame();
        updateStd.setVisible(true);
        updateStd.setFields(stList.get(tblStudent.getSelectedRow()));
        updateStd.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        updateStd.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
            }

            @Override
            public void windowClosing(WindowEvent e) {
            }

            @Override
            public void windowClosed(WindowEvent e) {
                loadStudent();
                loadUndergraduateStudent();
                loadPostgraduateStudent();
            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
        });
    }//GEN-LAST:event_btnUpdateStudentActionPerformed

    private void btnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudentActionPerformed
        StudentRegFrame newStd = new StudentRegFrame();
        newStd.setVisible(true);
        newStd.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        newStd.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
            }

            @Override
            public void windowClosing(WindowEvent e) {
            }

            @Override
            public void windowClosed(WindowEvent e) {
                loadStudent();
                loadUndergraduateStudent();
                loadPostgraduateStudent();
            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
        });
    }//GEN-LAST:event_btnAddStudentActionPerformed

    private void btnViewUndegraduateStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewUndegraduateStudentActionPerformed
        ViewUndergraduateStudentFrame viewStdU = new ViewUndergraduateStudentFrame();
        viewStdU.setVisible(true);
        viewStdU.setFields(UstList.get(tblUndergraduateStudent.getSelectedRow()));
        viewStdU.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnViewUndegraduateStudentActionPerformed

    private void btnUpdateUndegraduateStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUndegraduateStudentActionPerformed
        UpdateUndergraduateStudentFrame updateStdU = new UpdateUndergraduateStudentFrame();
        updateStdU.setVisible(true);
        updateStdU.setFields(UstList.get(tblUndergraduateStudent.getSelectedRow()));
        updateStdU.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        updateStdU.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
            }

            @Override
            public void windowClosing(WindowEvent e) {
            }

            @Override
            public void windowClosed(WindowEvent e) {
                loadUndergraduateStudent();
            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
        });
    }//GEN-LAST:event_btnUpdateUndegraduateStudentActionPerformed

    private void btnViewPostgraduateStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPostgraduateStudentActionPerformed
        ViewPostgraduateStudentFrame viewStdP = new ViewPostgraduateStudentFrame();
        viewStdP.setVisible(true);
        viewStdP.setFields(PstList.get(tblPostgraduateStudent.getSelectedRow()));
        viewStdP.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnViewPostgraduateStudentActionPerformed

    private void btnUpdatePostgraduateStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePostgraduateStudentActionPerformed
        UpdatePostgraduateStudentFrame updateStdP = new UpdatePostgraduateStudentFrame();
        updateStdP.setVisible(true);
        updateStdP.setFields(PstList.get(tblPostgraduateStudent.getSelectedRow()));
        updateStdP.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        updateStdP.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
            }

            @Override
            public void windowClosing(WindowEvent e) {
            }

            @Override
            public void windowClosed(WindowEvent e) {
                loadPostgraduateStudent();
            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
        });
    }//GEN-LAST:event_btnUpdatePostgraduateStudentActionPerformed

    private void btnViewLecturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewLecturerActionPerformed
        ViewLecturerFrame viewLec = new ViewLecturerFrame();
        viewLec.setVisible(true);
        viewLec.setFields(LecList.get(tblLecturer.getSelectedRow()));
        viewLec.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnViewLecturerActionPerformed

    private void btnViewInstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewInstructorActionPerformed
        ViewInstructorFrame viewIns = new ViewInstructorFrame();
        viewIns.setVisible(true);
        viewIns.setFields(InsList.get(tblInstructer.getSelectedRow()));
        viewIns.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnViewInstructorActionPerformed

    private void btnUpdateLecturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateLecturerActionPerformed
        UpdateLectureFrame updateLec = new UpdateLectureFrame();
        updateLec.setVisible(true);
        updateLec.setFields(LecList.get(tblLecturer.getSelectedRow()));
        updateLec.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        updateLec.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
            }

            @Override
            public void windowClosing(WindowEvent e) {
            }

            @Override
            public void windowClosed(WindowEvent e) {
                loadLecturer();
            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
        });
    }//GEN-LAST:event_btnUpdateLecturerActionPerformed

    private void btnUpdateInstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateInstructorActionPerformed
        UpdateInstructorFrame updateIns = new UpdateInstructorFrame();
        updateIns.setVisible(true);
        updateIns.setFields(InsList.get(tblInstructer.getSelectedRow()));
        updateIns.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        updateIns.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
            }

            @Override
            public void windowClosing(WindowEvent e) {
            }

            @Override
            public void windowClosed(WindowEvent e) {
                loadInstructor();
            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
        });
    }//GEN-LAST:event_btnUpdateInstructorActionPerformed

    private void btnUpdateSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateSubjectActionPerformed
        UpdateSubjectFrame updateCos = new UpdateSubjectFrame();
        updateCos.setVisible(true);
        updateCos.setFields(SubjectList.get(tblSubject.getSelectedRow()));
        updateCos.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        updateCos.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
            }

            @Override
            public void windowClosing(WindowEvent e) {
            }

            @Override
            public void windowClosed(WindowEvent e) {
                loadSubject();
                loadCourseReg();
            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
        });
    }//GEN-LAST:event_btnUpdateSubjectActionPerformed

    private void btnDeleteLecturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteLecturerActionPerformed
        DeleteLecturerFrame deleteLec = new DeleteLecturerFrame();
        deleteLec.setVisible(true);
        deleteLec.setFields(LecList.get(tblLecturer.getSelectedRow()));
        //deleteLec.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        deleteLec.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
            }

            @Override
            public void windowClosing(WindowEvent e) {
            }

            @Override
            public void windowClosed(WindowEvent e) {
                loadLecturer();
            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
        });
    }//GEN-LAST:event_btnDeleteLecturerActionPerformed

    private void btnDeleteInstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteInstructorActionPerformed
        DeleteInstructorFrame deleteIns = new DeleteInstructorFrame();
        deleteIns.setVisible(true);
        deleteIns.setFields(InsList.get(tblInstructer.getSelectedRow()));
        //deleteStd.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        deleteIns.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
            }

            @Override
            public void windowClosing(WindowEvent e) {
            }

            @Override
            public void windowClosed(WindowEvent e) {
                loadInstructor();
            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
        });
    }//GEN-LAST:event_btnDeleteInstructorActionPerformed

    private void btnDeleteSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSubjectActionPerformed
        DeleteSubjectFrame deleteCos = new DeleteSubjectFrame();
        deleteCos.setVisible(true);
        deleteCos.setFields(SubjectList.get(tblSubject.getSelectedRow()));
        //deleteStd.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        deleteCos.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
            }

            @Override
            public void windowClosing(WindowEvent e) {
            }

            @Override
            public void windowClosed(WindowEvent e) {
                loadSubject();
            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
        });
    }//GEN-LAST:event_btnDeleteSubjectActionPerformed

    private void btnMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainMenuActionPerformed
        HomeFrame n = new HomeFrame();
        n.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMainMenuActionPerformed

    private void btnDeleteCourseRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCourseRegActionPerformed
        int index3 = CourseRegList.get(tblCourseReg.getSelectedRow()).getIndexNo();
        int sem3 = CourseRegList.get(tblCourseReg.getSelectedRow()).getSemester();
        dbOps.deleteStuCourseReg(index3, sem3);
        dbOps.deleteResult(index3, sem3);
        loadCourseReg();
        loadMarkSheet();
    }//GEN-LAST:event_btnDeleteCourseRegActionPerformed

    private void btnAddMarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMarksActionPerformed
        AddMarksFrame addM = new AddMarksFrame();
        addM.setVisible(true);
        addM.setFields(MarksList.get(tblMarks.getSelectedRow()));
        addM.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        System.out.println("rrrr");
        addM.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
            }

            @Override
            public void windowClosing(WindowEvent e) {
            }

            @Override
            public void windowClosed(WindowEvent e) {
                loadMarkSheet();
            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
        });
    }//GEN-LAST:event_btnAddMarksActionPerformed

    private void btnUpdateMarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateMarksActionPerformed
        UpdateMarksFrame upM = new UpdateMarksFrame();
        upM.setVisible(true);
        upM.setFields(MarksList.get(tblMarks.getSelectedRow()));
        upM.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        upM.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
            }

            @Override
            public void windowClosing(WindowEvent e) {
            }

            @Override
            public void windowClosed(WindowEvent e) {
                loadMarkSheet();
            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
        });
    }//GEN-LAST:event_btnUpdateMarksActionPerformed

    private void btnRemoveMarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveMarksActionPerformed
        int index5 = MarksList.get(tblMarks.getSelectedRow()).getIndexNo();
        int sem5 = MarksList.get(tblMarks.getSelectedRow()).getSemester();
        dbOps.resetMarks(index5, sem5);
        loadMarkSheet();
    }//GEN-LAST:event_btnRemoveMarksActionPerformed

    private void btnSendEmail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendEmail1ActionPerformed
        SendEmail s = new SendEmail();

        String selected4 = MarksList.get(tblMarks.getSelectedRow()).getSendOrNot();
        int index4 = MarksList.get(tblMarks.getSelectedRow()).getIndexNo();
        int sem4 = MarksList.get(tblMarks.getSelectedRow()).getSemester();

        String rSub1 = MarksList.get(tblMarks.getSelectedRow()).getSubject1();
        String rSub2 = MarksList.get(tblMarks.getSelectedRow()).getSubject2();
        String rSub3 = MarksList.get(tblMarks.getSelectedRow()).getSubject3();
        String rSub4 = MarksList.get(tblMarks.getSelectedRow()).getSubject4();
        String rSub5 = MarksList.get(tblMarks.getSelectedRow()).getSubject5();
        String rSub6 = MarksList.get(tblMarks.getSelectedRow()).getSubject6();
        double rGPA = MarksList.get(tblMarks.getSelectedRow()).getGPA();
        String result = "-------------- Semester Result -----------------\n\n"
                + "\t  Subject 1 = " + rSub1 + "\n"
                + "\t  Subject 2 = " + rSub2 + "\n"
                + "\t  Subject 3 = " + rSub3 + "\n"
                + "\t  Subject 4 = " + rSub4 + "\n"
                + "\t  Subject 5 = " + rSub5 + "\n"
                + "\t  Subject 6 = " + rSub6 + "\n"
                + "\t  GPA       = " + rGPA + "\n\n"
                + " result send from NSBM resut Center";

        String email = MarksList.get(tblMarks.getSelectedRow()).getEmail();
        //s.send(email, result);
        //s.send("amith.liyanage.9@gmail.com", result);

        boolean se = s.send(email, result);
        if (se) {
            //Data Inserted Successfully
            if (selected4.equals("No")) {
                dbOps.updateMarksSend(index4, sem4, "Yes");
                loadMarkSheet();
            }
            JOptionPane.showMessageDialog(this, "Email send Successfully...");

        } else {
            //Data Insert not Successful
            JOptionPane.showMessageDialog(this, "Oops, Error occured while Sending Email");
            setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_btnSendEmail1ActionPerformed

    private void btnNotPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotPayActionPerformed
        String selected1 = CourseRegList.get(tblCourseReg.getSelectedRow()).getPayedOrNot();
        int index1 = CourseRegList.get(tblCourseReg.getSelectedRow()).getIndexNo();
        int sem1 = CourseRegList.get(tblCourseReg.getSelectedRow()).getSemester();
        if (selected1.equals("Yes")) {
            dbOps.updateCourseRegPay(index1, sem1, "No");
            loadCourseReg();
        }
    }//GEN-LAST:event_btnNotPayActionPerformed

    private void btnPayedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayedActionPerformed
        String selected2 = CourseRegList.get(tblCourseReg.getSelectedRow()).getPayedOrNot();
        int index2 = CourseRegList.get(tblCourseReg.getSelectedRow()).getIndexNo();
        int sem2 = CourseRegList.get(tblCourseReg.getSelectedRow()).getSemester();
        if (selected2.equals("No")) {
            dbOps.updateCourseRegPay(index2, sem2, "Yes");
            loadCourseReg();
        }
    }//GEN-LAST:event_btnPayedActionPerformed

    private void tblMarksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMarksMouseClicked
//        int rowIndex = tblMarks.getSelectedRow();
//        int colIndex = tblMarks.getSelectedColumn();
//        System.out.println(rowIndex+", "+colIndex);
    }//GEN-LAST:event_tblMarksMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminViewFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddInstructor;
    private javax.swing.JButton btnAddLecturer;
    private javax.swing.JButton btnAddMarks;
    private javax.swing.JButton btnAddStudent;
    private javax.swing.JButton btnAddSubject;
    private javax.swing.JButton btnDeleteCourseReg;
    private javax.swing.JButton btnDeleteInstructor;
    private javax.swing.JButton btnDeleteLecturer;
    private javax.swing.JButton btnDeleteStudent;
    private javax.swing.JButton btnDeleteSubject;
    private javax.swing.JButton btnMainMenu;
    private javax.swing.JButton btnNotPay;
    private javax.swing.JButton btnPayed;
    private javax.swing.JButton btnRemoveMarks;
    private javax.swing.JButton btnSendEmail1;
    private javax.swing.JButton btnUpdateInstructor;
    private javax.swing.JButton btnUpdateLecturer;
    private javax.swing.JButton btnUpdateMarks;
    private javax.swing.JButton btnUpdatePostgraduateStudent;
    private javax.swing.JButton btnUpdateStudent;
    private javax.swing.JButton btnUpdateSubject;
    private javax.swing.JButton btnUpdateUndegraduateStudent;
    private javax.swing.JButton btnViewInstructor;
    private javax.swing.JButton btnViewLecturer;
    private javax.swing.JButton btnViewPostgraduateStudent;
    private javax.swing.JButton btnViewStudent;
    private javax.swing.JButton btnViewSubject;
    private javax.swing.JButton btnViewUndegraduateStudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTabbedPane jPanal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelBackground;
    private javax.swing.JPanel jPanelTopBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel lblClose3;
    private javax.swing.JLabel lblMinimize3;
    private javax.swing.JTable tblCourseReg;
    private javax.swing.JTable tblInstructer;
    private javax.swing.JTable tblLecturer;
    private javax.swing.JTable tblMarks;
    private javax.swing.JTable tblPostgraduateStudent;
    private javax.swing.JTable tblStudent;
    private javax.swing.JTable tblSubject;
    private javax.swing.JTable tblUndergraduateStudent;
    // End of variables declaration//GEN-END:variables
}
