/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package takehomeassignment;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class UpdateSubjectFrame extends javax.swing.JFrame {

    DBOperation dbOps = new DBOperation();
    private String oldSubID;
    int mousepX;
    int mousepY;
    Subject course;
    
    /**
     * Creates new form UpdateSubjectFrame
     */
    public UpdateSubjectFrame() {
        initComponents();
    }
    
    void setFields(Subject co){
        course = co;
        oldSubID = co.getSubjectID();
        
        txtSubjectID.setText(co.getSubjectID());
        txtSubjectName.setText(co.getSubjectName());
        ddDegreeType.setSelectedItem(co.getDegree());
        ddYearType.setSelectedItem(co.getYear());
        ddSemType.setSelectedItem(co.getSemester());
        txtFees.setText(new Integer(co.getFees()).toString());
        txtLecturer.setText(co.getLecturer());
        txtInstructers.setText(co.getInstructors());
        txtTimeSchedule.setText(co.getTimeSchedule());
        ddNoOfAssingments.setSelectedItem(co.getNoOfAssignment());
        System.out.println(co.getNoOfAssignment());
        ddCredit.setSelectedItem(co.getCredit());
        System.out.println(co.getCredit());
        ddCompulsoryType.setSelectedItem(co.getcompulsoryType());
        txtPlaceLecture.setText(co.getPlaceLecture());
        txtPlacePractical.setText(co.getPlacePractical());
        txtNote.setText(co.getNote());   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTopBar2 = new javax.swing.JPanel();
        lblMinimize3 = new javax.swing.JLabel();
        lblClose1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSubjectID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFees = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ddDegreeType = new javax.swing.JComboBox();
        txtPlaceLecture = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ddNoOfAssingments = new javax.swing.JComboBox();
        txtSubjectName = new javax.swing.JTextField();
        txtInstructers = new javax.swing.JTextField();
        ddCredit = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        txtLecturer = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtPlacePractical = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtNote = new javax.swing.JTextArea();
        txtTimeSchedule = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        ddCompulsoryType = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        ddYearType = new javax.swing.JComboBox();
        ddSemType = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanelTopBar2.setBackground(new java.awt.Color(102, 255, 102));
        jPanelTopBar2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblMinimize3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblMinimize3.setForeground(new java.awt.Color(102, 102, 255));
        lblMinimize3.setText("-");
        lblMinimize3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimize3MouseClicked(evt);
            }
        });

        lblClose1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblClose1.setForeground(new java.awt.Color(102, 102, 255));
        lblClose1.setText("x");
        lblClose1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClose1MouseClicked(evt);
            }
        });

        jLabel15.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel15MouseDragged(evt);
            }
        });
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel15MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTopBar2Layout = new javax.swing.GroupLayout(jPanelTopBar2);
        jPanelTopBar2.setLayout(jPanelTopBar2Layout);
        jPanelTopBar2Layout.setHorizontalGroup(
            jPanelTopBar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopBar2Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblMinimize3)
                .addGap(10, 10, 10)
                .addComponent(lblClose1)
                .addContainerGap())
        );
        jPanelTopBar2Layout.setVerticalGroup(
            jPanelTopBar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelTopBar2Layout.createSequentialGroup()
                .addGroup(jPanelTopBar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMinimize3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblClose1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelTopBar2);
        jPanelTopBar2.setBounds(0, 0, 660, 30);

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Imprint MT Shadow", 0, 14), new java.awt.Color(0, 204, 102))); // NOI18N
        jPanel1.setToolTipText("");

        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Subject ID");

        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Subject Name");

        txtSubjectID.setBackground(new java.awt.Color(240, 240, 240));
        txtSubjectID.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtSubjectID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubjectIDActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Fees");

        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("Instructors");

        txtFees.setBackground(new java.awt.Color(240, 240, 240));
        txtFees.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtFees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFeesActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Place Lecture");

        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("Note");

        jLabel10.setForeground(new java.awt.Color(0, 0, 153));
        jLabel10.setText("Degree Type");

        ddDegreeType.setBackground(new java.awt.Color(92, 151, 191));
        ddDegreeType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CS", "IS" }));
        ddDegreeType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddDegreeTypeActionPerformed(evt);
            }
        });

        txtPlaceLecture.setBackground(new java.awt.Color(240, 240, 240));
        txtPlaceLecture.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtPlaceLecture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlaceLectureActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(0, 0, 153));
        jLabel11.setText("Lecturer");

        jLabel12.setForeground(new java.awt.Color(0, 0, 153));
        jLabel12.setText("Time Schedule");

        jLabel13.setForeground(new java.awt.Color(0, 0, 153));
        jLabel13.setText("No of Assignments");

        ddNoOfAssingments.setBackground(new java.awt.Color(92, 151, 191));
        ddNoOfAssingments.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        ddNoOfAssingments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddNoOfAssingmentsActionPerformed(evt);
            }
        });

        txtSubjectName.setBackground(new java.awt.Color(240, 240, 240));
        txtSubjectName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtSubjectName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubjectNameActionPerformed(evt);
            }
        });

        txtInstructers.setBackground(new java.awt.Color(240, 240, 240));
        txtInstructers.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtInstructers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInstructersActionPerformed(evt);
            }
        });

        ddCredit.setBackground(new java.awt.Color(92, 151, 191));
        ddCredit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        ddCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddCreditActionPerformed(evt);
            }
        });

        jLabel16.setForeground(new java.awt.Color(0, 0, 153));
        jLabel16.setText("Credits");

        txtLecturer.setBackground(new java.awt.Color(240, 240, 240));
        txtLecturer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtLecturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLecturerActionPerformed(evt);
            }
        });

        jLabel18.setForeground(new java.awt.Color(0, 0, 153));
        jLabel18.setText("Place Practical");

        txtPlacePractical.setBackground(new java.awt.Color(240, 240, 240));
        txtPlacePractical.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtPlacePractical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacePracticalActionPerformed(evt);
            }
        });

        txtNote.setBackground(new java.awt.Color(240, 240, 240));
        txtNote.setColumns(20);
        txtNote.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtNote.setRows(5);
        jScrollPane3.setViewportView(txtNote);

        txtTimeSchedule.setBackground(new java.awt.Color(240, 240, 240));
        txtTimeSchedule.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtTimeSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimeScheduleActionPerformed(evt);
            }
        });

        jLabel17.setForeground(new java.awt.Color(0, 0, 153));
        jLabel17.setText("Compulsory or Not?");

        ddCompulsoryType.setBackground(new java.awt.Color(92, 151, 191));
        ddCompulsoryType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Compulsory", "Optional" }));
        ddCompulsoryType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddCompulsoryTypeActionPerformed(evt);
            }
        });

        jLabel19.setForeground(new java.awt.Color(0, 0, 153));
        jLabel19.setText("Year");

        ddYearType.setBackground(new java.awt.Color(92, 151, 191));
        ddYearType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        ddYearType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddYearTypeActionPerformed(evt);
            }
        });

        ddSemType.setBackground(new java.awt.Color(92, 151, 191));
        ddSemType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));
        ddSemType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddSemTypeActionPerformed(evt);
            }
        });

        jLabel20.setForeground(new java.awt.Color(0, 0, 153));
        jLabel20.setText("Sem");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel10))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSubjectName)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtSubjectID, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtFees, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                            .addComponent(txtLecturer)
                                            .addComponent(ddDegreeType, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel19)
                                        .addGap(18, 18, 18)
                                        .addComponent(ddYearType, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel20)
                                        .addGap(18, 18, 18)
                                        .addComponent(ddSemType, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel16))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtInstructers)
                                    .addComponent(jScrollPane3)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ddCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPlaceLecture, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTimeSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addGap(23, 23, 23)
                                                .addComponent(ddNoOfAssingments, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel17)
                                                    .addComponent(jLabel18))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(txtPlacePractical, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 4, Short.MAX_VALUE))
                                                    .addComponent(ddCompulsoryType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))))
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSubjectID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSubjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ddDegreeType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(ddYearType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(ddSemType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtLecturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtInstructers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(ddNoOfAssingments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimeSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(ddCompulsoryType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ddCredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPlacePractical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18))
                    .addComponent(txtPlaceLecture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 600, 470));

        btnUpdate.setBackground(new java.awt.Color(31, 58, 147));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 590, 90, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(92, 151, 191));
        jLabel14.setText("Update Subject ");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 660, 720);

        setSize(new java.awt.Dimension(659, 638));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblMinimize3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimize3MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimize3MouseClicked

    private void lblClose1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClose1MouseClicked
        this.dispose();
    }//GEN-LAST:event_lblClose1MouseClicked

    private void jLabel15MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseDragged
        int cordinateX = evt.getXOnScreen();
        int cordinateY = evt.getYOnScreen();

        this.setLocation(cordinateX - mousepX , cordinateY - mousepY);
    }//GEN-LAST:event_jLabel15MouseDragged

    private void jLabel15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_jLabel15MousePressed

    private void txtSubjectIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubjectIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubjectIDActionPerformed

    private void txtFeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFeesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFeesActionPerformed

    private void ddDegreeTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddDegreeTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddDegreeTypeActionPerformed

    private void txtPlaceLectureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlaceLectureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlaceLectureActionPerformed

    private void ddNoOfAssingmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddNoOfAssingmentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddNoOfAssingmentsActionPerformed

    private void txtSubjectNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubjectNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubjectNameActionPerformed

    private void txtInstructersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInstructersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInstructersActionPerformed

    private void txtLecturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLecturerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLecturerActionPerformed

    private void txtPlacePracticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacePracticalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacePracticalActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        Subject c = new Subject();

        c.setOldCourseID(oldSubID);
        System.out.println("---->"+c.getOldCourseID());
        
        c.setSubjectID(txtSubjectID.getText());
        c.setSubjectName(txtSubjectName.getText());
        c.setDegree(ddDegreeType.getSelectedItem().toString());
        c.setFees(Integer.parseInt(txtFees.getText()));
        c.setLecturer(txtLecturer.getText());
        c.setInstructors(txtInstructers.getText());
        c.setTimeSchedule(txtTimeSchedule.getText());
        c.setNoOfAssignment(Integer.parseInt(ddNoOfAssingments.getSelectedItem().toString()));
        c.setCredit(Integer.parseInt(ddCredit.getSelectedItem().toString()));
        c.setcompulsoryType(ddCompulsoryType.getSelectedItem().toString());
        c.setPlaceLecture(txtPlaceLecture.getText());
        c.setPlacePractical(txtPlacePractical.getText());
        c.setNote(txtNote.getText());
        
        if(dbOps.updateSubject(c)){
            JOptionPane.showMessageDialog(this, "Successfully Update the record !!");
            this.dispose();

        }else{
            JOptionPane.showMessageDialog(this, "Error, while Updateing !!");
            setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtTimeScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimeScheduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimeScheduleActionPerformed

    private void ddCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddCreditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddCreditActionPerformed

    private void ddCompulsoryTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddCompulsoryTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddCompulsoryTypeActionPerformed

    private void ddYearTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddYearTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddYearTypeActionPerformed

    private void ddSemTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddSemTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddSemTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateSubjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateSubjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateSubjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateSubjectFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateSubjectFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox ddCompulsoryType;
    private javax.swing.JComboBox ddCredit;
    private javax.swing.JComboBox ddDegreeType;
    private javax.swing.JComboBox ddNoOfAssingments;
    private javax.swing.JComboBox ddSemType;
    private javax.swing.JComboBox ddYearType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelTopBar2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblClose1;
    private javax.swing.JLabel lblMinimize3;
    private javax.swing.JTextField txtFees;
    private javax.swing.JTextField txtInstructers;
    private javax.swing.JTextField txtLecturer;
    private javax.swing.JTextArea txtNote;
    private javax.swing.JTextField txtPlaceLecture;
    private javax.swing.JTextField txtPlacePractical;
    private javax.swing.JTextField txtSubjectID;
    private javax.swing.JTextField txtSubjectName;
    private javax.swing.JTextField txtTimeSchedule;
    // End of variables declaration//GEN-END:variables
}
